credentials:
  survey:
    apiKey: ENC[AES256_GCM,data:TKEZWPT2XvFCZkj49gnTw5X7C9vzjmJE5ShTJ4tYR+uRolvrDiLHIvUi42ukRvgG27947DkCPWRst09zeW/7,iv:02/kmUftVTcWIInp9NfzpD812zjlWaqm4JrFc4wUzrI=,tag:bJYpwL4jrrqctVRXKSmSuA==,type:str]
    token:
      publicKey: ENC[AES256_GCM,data:/KuEXB/3Oh+XCtWX27lbHmhZj91Nr9vqVS3WiTljk5tMC5YuUapb5whsPByjVAuVwYPqSi9dgGyyqXnuueMrNrtB67kqMWYoBnNwaz06zoQSiTbfWIjnGFlOkpW7LU+nirpBh2obkADkK2jIEfld/vlZTmXb+ec62tMIp+eUyxg7qEG11iDsTVmurZNGjPwQFeN9aM/9n8u1QLG6KBdb/ZPKdiSTOqZussIMXVcgO+MBKAM6DGK53Ji4hkizj//f/IgCJH76wwKP+RRCPYFj7qT6jrIhbuJX4cAiEw46PgImXVMW1SuSbo3p1AvusMkynjzp4TpyXzs+BsRGbT1R1AbVfPJRbSRvuhKrWrq3H38X2Txs6EWjDKhmH02GW4gw7vf1dztOxy0HEuy6CVZe62Nj9VWLgCbZBOu99R9m7n5VdKiJfLGn9BSivAZeT5WJxfXhxAOyVr9aFnGKQbnBdrIL/jFoelkbfKdl1eGmxj+IizP/ul4jyU788pW4NcIjnTAqaov8ofT9rYYnNqWUd8XPO859JECVqMIfRmpuPd1rFekm7RZNLelqDVkAkLhYv4GyTXn351W64xdw6YlBOQgRtQ==,iv:soqOsg9R9EKCW7Eqb240VTOH1bRNOypqMmiVYlJlgd8=,tag:HwEJbyk+E2bCWRcBHLNAKg==,type:str]
sops:
  kms:
    - arn: arn:aws:kms:ap-southeast-1:714417329994:key/f95830ba-ce2c-40e3-ac99-761cb3b6a078
      created_at: '2018-08-08T01:25:52Z'
      enc: AQICAHhboctRY7FEMb+0lyrJxvysTUQrRYAacDJsNTMkYA2LwAFzAup5T9xcfv/dHRMiDSVCAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMFe2bukb11+udAiqGAgEQgDvQFh0if3/sTQ1bT1yEUCo4ZHZpJzHDPm2XsgwAiU3G+06b6drNp6WNJQb/niTRIEZRLuQ6l4Pv5iR7gQ==
  gcp_kms: []
  lastmodified: '2018-08-08T01:25:53Z'
  mac: ENC[AES256_GCM,data:zGWrn3oIb3CZDiay4Z4LSrdUrWdN+6oTV8B0GZJl2zdZSD4b1KxgRK7Mg8zJYPrEkZK7wyUUoQpiLScgConGtvWqgrASEEh5VqkqC58394f5EmBc+ORVoJvHW1uXLApUA2HDgTeh2qyCnO+Q02Acp34ejnSlc5euqUVILEfssBM=,iv:MLAOrGRGlb5JFvnfKEsHOqkJB6/8Nwbi50XCPUG9wr0=,tag:k75UVY9/+trlH/7MIybNmQ==,type:str]
  pgp: []
  unencrypted_suffix: _unencrypted
  version: 3.0.5
