env: development
port: 3000
allowedOrigins:
  - .hktester.com
logger:
  logLevel: debug
  prettyPrint: true
services:
  survey:
    baseURL: https://stg-survey-api.hktester.com/v1.0/
    surveyCookie: hk01_survey_token
